version: "3.9"
services:
  auth-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.3.0
    restart: unless-stopped
    environment:
      # service settings
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_PASS_USER_HEADERS: "true"
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
      # allow validation of JWTs in Authorization HTTP header
      # https://medium.com/in-the-weeds/service-to-service-authentication-on-kubernetes-94dcb8216cdc#20d0
      OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: "true"

      # when authenticated, return a static 202 response
      # https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#forwardauth-with-static-upstreams-configuration
      OAUTH2_PROXY_UPSTREAMS: static://202

      # general cookie settings
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_COOKIE_EXPIRE: 30m
      OAUTH2_PROXY_COOKIE_REFRESH: 1m
      OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: "true"
      # base session cookie on Keycloak username (email not always set in Keycloak)
      OAUTH2_PROXY_USER_ID_CLAIM: preferred_username

      # OIDC integration settings
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: Keeycloak
      OAUTH2_PROXY_SCOPE: openid profile email
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.${IP}.nip.io/auth/realms/fEMR
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}

      # security settings
      OAUTH2_PROXY_COOKIE_DOMAINS: .${IP}.nip.io
      OAUTH2_PROXY_WHITELIST_DOMAINS: .${IP}.nip.io
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}

    labels:
      traefik.enable: "true"
      traefik.http.routers.auth-proxy.rule: Host(`auth-proxy.${IP}.nip.io`) || PathPrefix(`/oauth2`)
      traefik.http.routers.auth-proxy.middlewares: auth-headers
      traefik.http.routers.auth-proxy.entrypoints: websecure
      traefik.http.routers.auth-proxy.tls.certresolver: letsencrypt
      traefik.http.routers.auth-proxy.tls: "true"

      # oauth2-proxy does not EXPOSE the ports it listens on, requiring explicit traefik configuration
      traefik.http.services.auth-proxy.loadbalancer.server.port: 4180

      traefik.http.middlewares.oidc-auth.forwardAuth.address: http://auth-proxy:4180/
      traefik.http.middlewares.oidc-auth.forwardAuth.trustForwardHeader: "true"
      # TODO block Authorization header for postgrest using custom middleware
      traefik.http.middlewares.oidc-auth.forwardAuth.authResponseHeaders: X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Access-Token,Authorization


      # TODO move to common config
      # best-practice HTTPS headers
      traefik.http.middlewares.auth-headers.headers.forceSTSHeader: "true"
      traefik.http.middlewares.auth-headers.headers.sslHost: auth-proxy.${IP}.nip.io
      traefik.http.middlewares.auth-headers.headers.stsIncludeSubdomains: "true"
      traefik.http.middlewares.auth-headers.headers.stsPreload: "true"
      traefik.http.middlewares.auth-headers.headers.sslRedirect: "true"
      traefik.http.middlewares.auth-headers.headers.stsSeconds: 315360000
      traefik.http.middlewares.auth-headers.headers.browserXssFilter: "true"
      traefik.http.middlewares.auth-headers.headers.contentTypeNosniff: "true"
      traefik.http.middlewares.auth-headers.headers.frameDeny: "true"
    networks:
      ingress:
      internal:

  whoami:
    image: containous/whoami
    labels:
      traefik.enable: "true"
      traefik.http.routers.whoami.rule: Host(`whoami.${IP}.nip.io`)
      traefik.http.routers.whoami.middlewares: oidc-auth
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.tls.certresolver: letsencrypt
      traefik.http.routers.whoami.tls: "true"
    networks:
      ingress:
      internal:

  postgrest:
    image: postgrest/postgrest
    environment:
      PGRST_DB_URI: postgres://app_user:secret@postgres:5432/app_db
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
    depends_on:
      - postgres
    labels:
      traefik.enable: "true"
      traefik.http.routers.postgrest.rule: Host(`postgrest.${IP}.nip.io`)
      # chain postgrest-specifc middleware, after oidc-auth
      traefik.http.routers.postgrest.middlewares: oidc-auth,remove-authz-header
      traefik.http.routers.postgrest.entrypoints: websecure
      traefik.http.routers.postgrest.tls.certresolver: letsencrypt
      traefik.http.routers.postgrest.tls: "true"

      # unset Authorization header on all requests to postgrest
      # postgrest implements its own auth which conflicts with oauth2-proxy
      traefik.http.middlewares.remove-authz-header.headers.customrequestheaders.Authorization: ""

    networks:
      ingress:
      internal:

  postgres:
    image: postgres:${POSTGRES_IMAGE_TAG:-15}
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      internal:

volumes:
  postgres-data: {}

networks:
  # internal network for backing services
  internal:

  # ingress network
  ingress:
    name: external_web
    # TODO find fix
    # `docker-compose` expects string, `docker compose` expects boolean
    # external: "true"
    external: true
